# Generated by Django 4.0.3 on 2022-03-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
